### ISSUE TITLE
Improve your ES6

### ISSUE THREAD

**Issue by Yurickh** [teogenesmoura/votechain#2]
I have a few points on how to improve your javascript overall. I might open another issue for specific points if I happen to find them.

## Forget about var
In ES6, you can declare variables using `let` or `const`. `let` pretty much is the `var2.0`. I really can't think of a situation where you **need** to use `var` instead of `let`. Anyway, `let` has a better hoisting strategy and will lead to less buggy code. 
In the other hand, use `const` whenever you can. All `require` should be stored in `const`s, unless...

## Use ES6 modules
This is kind of optional, since node's support to ES6 modules is not ideal.. but, they're beautiful as fuck. I just feel better writing
```javascript
import x from 'y'
```
than
```javascript
const x = require('y')
```
Anyway, skip this if you're not interested in attaching a transpiler to your project, and want to stick to node's version of ES6.

## Stop using `for`
I know `for in` sounds resonant with other languages you know, but whenever you need to loop an array, prefer the `forEach` method, or the `indexOf`, `map`, `filter` dedicated methods. This is due to the way javascript resolves scope. Using these methods will, in the long run, reduce the chance you write a buggy code just because the language doesn't make sense sometimes.

For example, in your `election.js` file, lines 26:30, you have:
```javascript
for(var voter in this.voters){
	if (voter.name == name) {
		return "voter already exists";
	}
}
```
the same code could be written like:
```javascript
if(this.voters.find((voter) => voter.name === name)) {
    return "voter already exists";
}
```

## Use more arrow functions
Arrow functions are one of the most fantastic features of ES6, and you should use them more often. Not only they let you write callbacks using less notation, which pays off lines of codes in the long run, but they also resolves the problem that `function` has with `this`.
For example, the above code (the one that finds the voter by name) could be neatly written instead of this freak:
```javascript
if(this.voters.find(function(voter) { return voter.name === name })) {
    return "voter already exists";
}
```
Thank god you didn't need to use `this` inside of that function, because it would default to `undefined`, instead of what you would expect.

## But know when to use them
Arrow functions provide clarity, compactness and scope safety, but not every time is the good time to use them. Use the standard `function` keyword when declaring functions in the global scope to make use of its hoisting capabilities.

## Always compare with `===`
The `==` operator is not at all reliable. Use the `===` operator whenever possible. In case you don't know, the `===` operator also looks for the type of the two objects. e.g. `10 == '10'` is `true` while `10 === '10'` is `false`.
Javascript has some odd behavior with types, so it's better to ensure you know what you're comparing with.

**Comment by teogenesmoura** [comment]
Dude, such an awesome feedback! Thank you so much :)
I'll update the code to reflect your suggestions as soon as possible!

**Comment by Yurickh** [comment]
I'll be closing this, as it's almost 3 years old :)~ feel free to reopen if you want more input
